@startmindmap
* Document Root
** STELLA_REFLECTION
** README
** CLAUDE
** ruff_formatter_research
** projects
*** README
*** constellation_adventure
**** README
**** CONTRIBUTING
**** docs
***** refactoring_proposal
***** pre_stream_checklist
***** 3_person_chat_test_20250625
***** character_settings
***** tech_stack_verification
***** pm_guidelines
***** session_2_retrospective
***** session_1_retrospective
***** characters
****** stella_detailed
****** seira_detailed
**** public
***** sounds
****** README
*** star_tactics_room
**** star_tactics_room
***** README
***** examples
****** README
** memories
*** character_relationships
*** personality_notes
*** speech_patterns
*** character_details
*** background_story
*** behavioral_patterns
*** important_events
*** indexes
**** link_analysis_report
** docs
*** coding_best_practices
*** uv_best_practices
*** knowledge_management_design
*** workspace_organization_guide
** star_stories
*** 星にまつわる面白い話10選
** tools
*** doc_analyzer
**** README
**** CONTRIBUTING
@endmindmap